### ISSUE TITLE
VITS模型放在mods目录下没反应

### ISSUE THREAD

**Issue by zwluoqi** [NaruseMioShirakana/MoeVoiceStudio#31]
**Describe the bug**
如题所述，按照格式写了json文件，打开exe没报错了，也没反应。

![image](https://user-images.githubusercontent.com/3363485/235449075-fadbaa2f-4987-4263-955b-5878c7c1b178.png)

![image](https://user-images.githubusercontent.com/3363485/235449086-c954eb2a-e912-45dd-b88e-a2ec5feb35aa.png)
![image](https://user-images.githubusercontent.com/3363485/235449118-2e8ca66b-0130-41ba-b978-97502cfaec5b.png)

![image](https://user-images.githubusercontent.com/3363485/235449174-03ae8453-2294-4dcd-80e8-ef751ded959a.png)

**Comment by gak123** [comment]
但凡看完readme也提不出这种**问题来，MoeVS只支持onnx模型!!!!!!!

**Comment by Yumemi8** [comment]
请将您的模型先onnx化

**Comment by Erythrocyte3803** [comment]
建议先仔细认真看看readme，开头大字写着 要转成onnx

**Comment by zwluoqi** [comment]
谢谢 看到了
