### ISSUE TITLE
readme里面描述的一些支持的模型在源代码里面没有。

### ISSUE THREAD

**Issue by zwluoqi** [NaruseMioShirakana/MoeVoiceStudio#32]
能正常使用exe支持RVC模型的转换，但是我发现最新的代码里面没有相关的代码。
![image](https://user-images.githubusercontent.com/3363485/236105840-e6d3a4a6-f3e1-42ab-957d-b0cd36483918.png)

**Comment by NaruseMioShirakana** [comment]
因为最新的代码我没有推上来，最新的代码会在MoeVS发布时推送

**Comment by NaruseMioShirakana** [comment]
源代码已经更新
