### ISSUE TITLE
同一个RVC的ONNX模型在之前的moess-win7里面可以用，换到这个里面报错了

### ISSUE THREAD

**Issue by zwluoqi** [NaruseMioShirakana/MoeVoiceStudio#37]
模型配置:
```
    "Folder" : "march7",
    "Name" : "march7",
    "Type" : "RVC",
    "Rate" : 48000,
    "Hop" : 320,
    "Cleaner" : "",
    "Hubert": "hubert4.0",
    "Diffusion": false,
    "CharaMix": true,
    "Volume": false,
    "HiddenSize": 256,
    "Characters" : ["march7"]
```
模型地址：https://huggingface.co/spaces/qinzhu/girlfriend/resolve/main/march7_RVC.onnx
错误信息:
![image](https://github.com/NaruseMioShirakana/MoeVoiceStudio/assets/3363485/caba50fb-6d01-416d-9856-e49f963a3b60)
![image](https://github.com/NaruseMioShirakana/MoeVoiceStudio/assets/3363485/3211143c-acf4-49d9-9ab8-db2856bd9009)

**Comment by NaruseMioShirakana** [comment]
这个问题应该是f0的输入顺序错了，RVC的f0有两个，一个是int64类型（1-255）的nsff0，一个是float类型的单位为赫兹的f0，可能新版之中我搞乱了这两者的顺序（）

**Comment by NaruseMioShirakana** [comment]
我再看了一下，f0输入应该没问题，这里的问题应该是角色混合，只有使用了角色混合方案导出的模型才可以使用角色混合，也就是CharaMix这一项。
将CharaMix设置为false再试一试

**Comment by zwluoqi** [comment]
是的，改了之後正常了，可以關了，謝謝。
