### ISSUE TITLE
Core分支编译失败

### ISSUE THREAD

**Issue by Eragon-Brisingr** [NaruseMioShirakana/MoeVoiceStudio#43]
MoeVoiceStudioCore分支的main.cpp还是对QT有依赖，例如`#include <QApplication>`，请问必须依赖QT是设计如此吗？

**Comment by NaruseMioShirakana** [comment]
需要你自己编写软件，MoeVoiceStudioCore是一个类似于Lib的存在

**Comment by Eragon-Brisingr** [comment]
请问下Core分支中对QT的依赖是不会移除的吗？假如是按Lib设计的话依赖是不是尽可能少会比较好？

**Comment by NaruseMioShirakana** [comment]
已经移除了
