### ISSUE TITLE
请问`转换ONNX的程序`在哪？

### ISSUE THREAD

**Issue by Eragon-Brisingr** [NaruseMioShirakana/MoeVoiceStudio#45]
> 模型需要转换为ONNX模型，转换ONNX的程序我已经pull到每个项目的源仓库了，PTH不能直接用！！！！！！！！！！！！！

请问ReadMe中提到的`pth转换ONNX的程序`在哪里？

**Comment by LovelyA72** [comment]
+1, 我也找不到转换onnx的程序。已经搜索整个仓库了还是找不到。

**Comment by sekkit** [comment]
+1，我也找不到

**Comment by Maplespe** [comment]
搜索export_onnx.py
