### ISSUE TITLE
RVC 的json模板有误

### ISSUE THREAD

**Issue by ZYFDroid** [NaruseMioShirakana/MoeVoiceStudio#52]
![image](https://github.com/NaruseMioShirakana/MoeVoiceStudio/assets/39429452/259a89d3-d4ce-4a2c-a9a5-6608d80650d2)
如图，这个字段为true时，根据代码，软件会将其识别成SoVits模型（在加载模型的时候提示找不到 xxx_SoVits.onnx）
![image](https://github.com/NaruseMioShirakana/MoeVoiceStudio/assets/39429452/2d9a3e02-a43b-4399-9ad7-5ef415389380)

**Comment by NaruseMioShirakana** [comment]
马上修复（）
