### ISSUE TITLE
error when use cuda

### ISSUE THREAD

**Issue by kqTang** [NaruseMioShirakana/MoeVoiceStudio#57]
环境创建失败!
OrtException:
[ln "EnwManager.cpp" Line 68]
D: a work)1s onnxruntime core session(provider bridge ort.cc:1209
onnxruntimeProviderLibrary..Get [ONNXRuntimeError] : 1 : FAIL :
loadLibrary failed with error 126 " when trying to load
CUsers Administrator Downloads MoeVoicestudio.-1TS MoeVoicest
udio - T1s onnxruntime providers cuda.dll
![微信截图_20240306234003](https://github.com/NaruseMioShirakana/MoeVoiceStudio/assets/77558635/f9fc45db-5a40-4e3e-86e0-cd4b35f86984)

**Comment by kqTang** [comment]
> 环境创建失败! OrtException: [ln "EnwManager.cpp" Line 68] D: a work)1s onnxruntime core session(provider bridge ort.cc:1209 onnxruntimeProviderLibrary..Get [ONNXRuntimeError] : 1 : FAIL : loadLibrary failed with error 126 " when trying to load CUsers Administrator Downloads MoeVoicestudio.-1TS MoeVoicest udio - T1s onnxruntime providers cuda.dll ![微信截图_20240306234003](https://private-user-images.githubusercontent.com/77558635/310560444-f9fc45db-5a40-4e3e-86e0-cd4b35f86984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mzk5MTksIm5iZiI6MTcwOTczOTYxOSwicGF0aCI6Ii83NzU1ODYzNS8zMTA1NjA0NDQtZjlmYzQ1ZGItNWE0MC00ZTNlLTg2ZTAtY2Q0YjM1Zjg2OTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE1NDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZTQ5OGVkODU1N2E1ODk1ODRlODA0YzNjMjQ4NzQxNTAzYWZhYzlkYTJhZjY1NjQ1MjFkZTNjZTI5MTg2MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._98DLQ96wK0feYqkD0znT3Y1ND4T9MsKiSPkmw7pZ_4)

**Comment by NaruseMioShirakana** [comment]
Because of CUDA Minor Version Compatibility, ONNX Runtime built with CUDA 11.8 should be compatible with any CUDA 11.x version. Please reference [Nvidia CUDA Minor Version Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/#minor-version-compatibility).
